# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'collectionView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for collectionView
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'Firebase/Database'
pod 'Firebase/Firestore'

end
